### ISSUE TITLE
【エラー】run gate_test.rb

### ISSUE THREAD

**Issue by Saoki11111** [Saoki11111/learn-ruby#1]
Run options: --seed 6354

# Running:

E

Error:
GateTest#test_umeda_to_mikuni_when_fare_is_not_enough:
TypeError: nil can't be coerced into Integer
    /Users/s_aoki/workspace/ruby/ruby-book/lib/gate.rb:22:in `-'
    /Users/s_aoki/workspace/ruby/ruby-book/lib/gate.rb:22:in `calc_fare'
    /Users/s_aoki/workspace/ruby/ruby-book/lib/gate.rb:14:in `exit'
    /Users/s_aoki/workspace/ruby/ruby-book/test/gate_test.rb:33:in `test_umeda_to_mikuni_when_fare_is_not_enough'

bin/rails test Users/s_aoki/workspace/ruby/ruby-book/test/gate_test.rb:27

E

Error:
GateTest#test_gate:
TypeError: nil can't be coerced into Integer
    /Users/s_aoki/workspace/ruby/ruby-book/lib/gate.rb:22:in `-'
    /Users/s_aoki/workspace/ruby/ruby-book/lib/gate.rb:22:in `calc_fare'
    /Users/s_aoki/workspace/ruby/ruby-book/lib/gate.rb:14:in `exit'
    /Users/s_aoki/workspace/ruby/ruby-book/test/gate_test.rb:17:in `test_gate'

bin/rails test Users/s_aoki/workspace/ruby/ruby-book/test/gate_test.rb:11

Finished in 0.001197s, 1670.8437 runs/s, 0.0000 assertions/s.
2 runs, 0 assertions, 0 failures, 2 errors, 0 skips

**Comment by Saoki11111** [comment]
https://github.com/Saoki11111/learn-ruby/commit/e049ae0819b74ae54bfa07de052e01719a2369cc#diff-d735951548148e5aba9fa9b7ace3b8e4

こちらにて対応

```
  def stamp(name)
 -  @stamp_at = name
 +  @stamped_at = name
  end
```
typoを修正
